### ISSUE TITLE
New Design for our Biometrics SDK

### ISSUE THREAD

**Issue by migueltrevinom** [Open-Verifik/web-sdk#1]
## DESCRIPTION

Right now the logic for "D Biometrics it's purely using the API, we need to improve this logic in order to do this using the phone's camera, check Camilo design and create this "SDK"

https://www.figma.com/file/ASqLZFmf2IcabX4KHHDcbB/Isolated-Functionalities?type=design&node-id=3%3A12&mode=design&t=ZKGRXHAVsyRf9mhd-1

![Image](https://user-images.githubusercontent.com/9138358/252175009-8f28b61e-0258-4f2c-9376-8a1cad201e6d.png)

**Comment by migueltrevinom** [comment]
https://github.com/Open-Verifik/web-sdk/assets/9138358/2618efbf-2f21-402e-acc0-05d26bc121ed

I like this design!

**Comment by CamiloMat** [comment]
A much more modern design was developed and adapted to give a professional approach. Both for 2D facial scans and for documents.



![Image](https://github.com/Open-Verifik/web-sdk/assets/138621042/fe7be5b7-fe7f-4c50-8dab-66658107ae07)



You can find the designs at the next Link:

https://www.figma.com/file/ASqLZFmf2IcabX4KHHDcbB/Isolated-Functionalities?type=design&node-id=3%3A12&mode=design&t=m7grtrCYGCywWmnW-1
