### ISSUE TITLE
Login - Improvements for the current logic of the form

### ISSUE THREAD

**Issue by NicolasHT95** [Open-Verifik/web-sdk#25]
## DESCRIPTION

We are going to make some adjustments requested by Johan, the idea it's to improve the UX, so customers can have more options if they made a mistake.

## TO-DO

In the current login (1) we need to make the following updates:

- If the user change the countryCode, we need to reset the timers, this is in case they select an incorrect param.
- Reduce the timers for resend OTP's right now we have 10 minutes to way for another OTP, we must reduce it to 90 seconds.

## (1) Current login

![Image](https://github.com/Open-Verifik/web-sdk/assets/138807516/0dca5841-a654-42c6-850f-f7bd950a3694)

**Comment by migueltrevinom** [comment]
done
