### ISSUE TITLE
Smart acces -Fix the UI when you only have a face recognition

### ISSUE THREAD

**Issue by NicolasHT95** [Open-Verifik/web-sdk#28]
## DESCRIPTION

We made with Camilo an smart access review checking for improvements and bugs, the idea it's to enhance the UI.

## TO-DO

Check the design made by Felix and try to implement it in the current flow of the UI, if there's something that you don't like or don't match speak directly with Felix to make the corresponding fixes

https://www.figma.com/file/MkfWoBcPNemiijxodWJ2Da/Apps-V-1.0-(Part-2)?type=design&node-id=1132-17445&mode=design&t=iC96oosa1v8VxJpR-0

![Image](https://github.com/Open-Verifik/app.verifik.co/assets/138807516/d679fb02-1e9a-4a45-bc0c-203f853e8034)

**Comment by migueltrevinom** [comment]
I did fix also removing the tabs if only email is enabled (tabs would make sense if we have 2 options to pick from)

**Comment by migueltrevinom** [comment]
Check it on the sandbox please @NicolasHT95

**Comment by NicolasHT95** [comment]
**QA was successful**
